apiVersion: v1
kind: Namespace
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: knative-sources

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller-manager
  namespace: knative-sources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources/status
  - camelsources/finalizers
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - camel.apache.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    duck.knative.dev/source: "true"
    eventing.knative.dev/release: devel
  name: eventing-contrib-camel-source-observer
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: camel-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: camel-controller
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
  name: eventing-sources-camel-controller-addressable-resolver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
subjects:
- kind: ServiceAccount
  name: camel-controller-manager
  namespace: knative-sources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    duck.knative.dev/source: "true"
  name: camel-source-observer
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - camelsources
  verbs:
  - get
  - list
  - watch

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    duck.knative.dev/source: "true"
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: camelsources.sources.eventing.knative.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: CamelSource
    plural: camelsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            ceOverrides:
              description: Defines overrides to control modifications of the event
                sent to the sink.
              type: object
            sink:
              description: Reference to an object that will resolve to a domain name
                to use as the sink.
              type: object
            source:
              properties:
                flow:
                  type: object
                integration:
                  type: object
              type: object
          required:
          - source
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
          type: object
  version: v1alpha1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  ports:
  - name: https-camel
    port: 443
  selector:
    control-plane: camel-controller-manager

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    contrib.eventing.knative.dev/release: "v0.11.0"
    control-plane: camel-controller-manager
  name: camel-controller-manager
  namespace: knative-sources
spec:
  selector:
    matchLabels:
      control-plane: camel-controller-manager
  serviceName: camel-controller-manager
  template:
    metadata:
      labels:
        control-plane: camel-controller-manager
    spec:
      containers:
      - image: registry.cn-chengdu.aliyuncs.com/ysjjovo/eventing-contrib-camel-source-cmd-controller:0.11.0
        name: manager
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
      serviceAccount: camel-controller-manager
      terminationGracePeriodSeconds: 10

---
