apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.azk8s.cn/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"
