apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-service-example
  namespace: default
spec:
  template:
    metadata:
      name: stock-service-example-first
    spec:
      containers:
        - image: registry.cn-chengdu.aliyuncs.com/kn-sample/rest-api-go
          env:
            - name: RESOURCE
              value: stock
